---
title: 'MVA Week 4: ICA exercise 1'
author: "Kelly Williams"
date: "16/03/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results='hide'}
# Initialise

# Clear environment
rm(list=ls())
# Clear all plots
if(!is.null(dev.list())) dev.off()

# Install packages
library(tuneR)
library(fastICA)

```

Need to generate $n=500$ values for $X_1=cos(t)$ and $X_2=e^{-t}-5e^{-t/5}$. Assume that $t = 1,2,...,500$ is generated by a standard normal distribution.

```{r}

t <- 1:500

X_1 <- cos(t)

X_2 <- exp(-t) - 5*exp(-t/5)

X <- cbind(X_1, X_2)
X_ts = as.ts(X)
plot(X_ts)

```

Now let $S_1(t)=0.7X_1(t) + 0.4X_2(t)$ and $S_2=0.2X_1(t)-0.5X_2(t)$.

```{r}

S_1 <- 0.7*X_1 + 0.4*X_2

S_2 <- 0.2*X_1 - 0.5*X_2

S = cbind(S_1, S_2)
head(S)

S_ts = as.ts(S)
plot(S_ts)

```

Now use the FastICA algorithm to perform an ICA of the resulting data. 

```{r}

fastica = fastICA(S,2)
IC_s = fastica$S
IC_ts = as.ts(IC_s)
plot(IC_ts)

```

Can see from the plots that we have successfully extracted $X_1$ and $X_2$ up to rotation. 


